---
abstract: 'Perl module to parse Cadence synthesis tool logfiles'
author:
  - 'Lieven Hollevoet <hollie@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Output: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Cadenceparser
requires:
  Carp: 0
  Data::Dumper: 0
  Getopt::Std: 0
  Pod::Help: 0
  autodie: 0
  constant: 0
  perl: 5.012
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/hollie/text-cadenceparser-perl/issues
  repository: git://github.com/hollie/text-cadenceparser-perl.git
version: 1.07
